repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: [ --fix ]

  - repo: local
    hooks:
      - id: poetry-pytest
        name: Run Unit Tests (Poetry)
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
        types_or: [python, toml]

      - id: poetry-lock-check
        name: Check Poetry Lock File
        entry: bash -c 'poetry check'
        language: system
        files: ^(pyproject\.toml|poetry\.lock)$